### ISSUE TITLE
Example command does not work with long user/group IDs

### ISSUE THREAD

**Issue by nicbou** [minidocks/images#1]
To run the unpaper container, I ran the following command:

```
sudo docker run -e SUEXEC=$(id -u):$(id -g) -v pdfs:/pdfs unpaper /pdfs
```

This resulted in the following error message:

```
addgroup: number 1694527156 is not in 0..256000 range
```

The message is self-explanatory. It seems like the UID/GID can't exceed a certain value in the container, but can in MacOS.

**Comment by hason** [comment]
Fixed
